### ISSUE TITLE
Where are the raw images?

### ISSUE THREAD

**Issue by FightingForLiving** [git-davi/Towards-Real-Scene-Super-Resolution-with-Raw-Images#1]
I have download the training dataset(13040 training and 150 validataion images), but there are only GT, ISP and TrainingSet in the TESTING and TRAINING folders. I can't find the raw images. Where are they?

**Comment by git-davi** [comment]
I'm not the developer of this repo, the only reason I published this was beacause I've found hard to get this code online.
By the way the images you have I suppose are in RAW format! What are the extensions of the files?
Check in this list : https://en.wikipedia.org/wiki/Raw_image_format
