### ISSUE TITLE
Can you provide the BaiduNetDisk link of the training dataset？

### ISSUE THREAD

**Issue by scape1989** [git-davi/Towards-Real-Scene-Super-Resolution-with-Raw-Images#2]
Can you provide the BaiduNetDisk link of the training dataset？ I can not download them from google drive

**Comment by git-davi** [comment]
I do not have any, sorry. Drive is telling to retry later.
Btw as I say in the main repo this is not my work.
I've just published it to make the easier for people to find the code.
