### ISSUE TITLE
how to generate degraded low-resolution raw images?

### ISSUE THREAD

**Issue by liyuanyaun** [git-davi/Towards-Real-Scene-Super-Resolution-with-Raw-Images#3]
hi, could you pls offer the code or some idea to generate degraded low-resolution raw images? i want to create my own train dataset? thank you very much @git-davi

**Comment by git-davi** [comment]
Sorry, I do not have any code but I can suggest to you to open the image in python then use `cv2.resize(...)` to reduce your image resolution.
Take a look at rawpy module and [here](https://towardsdatascience.com/reading-an-image-in-python-without-using-special-libraries-534b57de7dd4)

**Comment by liyuanyaun** [comment]
> Sorry, I do not have any code but I can suggest to you to open the image in python then use `cv2.resize(...)` to reduce your image resolution.
> Take a look at rawpy module and [here](https://towardsdatascience.com/reading-an-image-in-python-without-using-special-libraries-534b57de7dd4)
but in rawsr paper of sensetime, it geenerate lr-raw from the hr-raw，its describraton is not very clear, would you think about the process of generation?
